### ISSUE TITLE
After first run, plugin crashes because `options.icon` was deleted

### ISSUE THREAD

**Issue by jonathaningram** [easthing/pwa-manifest-webpack-plugin#1]
Here https://github.com/easthing/pwa-manifest-webpack-plugin/blob/master/index.js#L86 you delete `this.options.icon`.

Later, after the first run, here https://github.com/easthing/pwa-manifest-webpack-plugin/blob/master/index.js#L50 you try and access `this.options.icon` again, but it has been deleted.

Not sure exactly what the solution is so I haven't given a PR, but possibly you could copy `this.options` into `content` here https://github.com/easthing/pwa-manifest-webpack-plugin/blob/master/index.js#L36 and then delete from `content` instead.

**Comment by easthing** [comment]
`this.options.icon` is a temporary variable, please copy your error information.

**Comment by jonathaningram** [comment]
Sorry I didn't give you a detailed report, it's pretty simple in that `this.options.icon` is deleted, but then referred to again later, so the error is just about reading from an undefined prop.

```
/app/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'sizes' of undefined
    at PwaManifestWebpackPlugin.genIcons (/app/node_modules/pwa-manifest-webpack-plugin/index.js:58:32)
    at Compiler.<anonymous> (/app/node_modules/pwa-manifest-webpack-plugin/index.js:29:10)
    at Compiler.next (/app/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.compiler.plugin (/app/robots-txt-webpack-plugin/index.js:51:7)
    at Compiler.next (/app/node_modules/tapable/lib/Tapable.js:69:14)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/app/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:564:21)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:691:18)
```

Also, the error won't happen on the first run, it will only happen when webpack recompiles (e.g. save one of your JS files so webpack rebuilds).

Again, sorry for the non-PR, I can't do one at the moment, but here's a working `index.js`.

Notes:

- it's formatted with https://github.com/jlongster/prettier so the diff is not clean, apologies there
- it has to get a copy of sizes since the array is later modified by some code `var sizes = this.options.icon.sizes.slice();`. we need the copy, otherwise subsequent runs will see that `this.options.icon.sizes` has been emptied
- it removes lodash and just uses `Object.assign` directly
- it creates `content` by instead cloning the options: `var contents = Object.assign({}, this.options);`
- and then only deleting the icon when in the output function `delete contents.icon;` (so that the options are never touched, only when outputting)
- and of course it removes the `delete this.options.icon` at the end of `genIcons`

```js
var mime = require("mime");
var lwip = require("lwip");

function PwaManifestWebpackPlugin(options) {
  this.options = Object.assign(
    {
      filename: "manifest.json",
      orientation: "portrait",
      display: "standalone",
      icons: []
    },
    options || {}
  );

  const defaultIconSizes = [36, 48, 72, 96, 144, 192];
  if (typeof this.options.icon === "string") {
    this.options.icon = {
      src: this.options.icon,
      sizes: defaultIconSizes
    };
  }
}

PwaManifestWebpackPlugin.prototype.apply = function(compiler) {
  var self = this;
  compiler.plugin("emit", function(compilation, callback) {
    self.genIcons(compiler, compilation, function() {
      self.createManifest(compilation);
      callback();
    });
  });
};

PwaManifestWebpackPlugin.prototype.createManifest = function(compilation) {
  var filename = this.options.filename;
  delete this.options.filename;
  var contents = Object.assign({}, this.options);
  delete contents.icon;

  compilation.assets[filename] = {
    source: function() {
      return JSON.stringify(contents, null, 2);
    },
    size: function() {
      return JSON.stringify(contents).length;
    }
  };
};

PwaManifestWebpackPlugin.prototype.genIcons = function(
  compiler,
  compilation,
  callback
) {
  var self = this;
  var sizes = this.options.icon.sizes.slice();
  var src = this.options.icon.src;
  var outputPath = compiler.options.output.path;

  // liwp library only single process, so one by one recursive processing
  function resize(image, sizes) {
    var type = mime.lookup(src);
    var ext = mime.extension(type);
    var size = sizes.pop();
    var filename = "icon_" + size + "x" + size + "." + ext;
    self.options.icons.push({
      src: filename,
      sizes: size + "x" + size,
      type: type
    });

    image.resize(size, size, function(err, image) {
      image.toBuffer(ext, function(err, buffer) {
        compilation.assets[filename] = {
          source: function() {
            return buffer;
          },
          size: function() {
            return buffer.length;
          }
        };
        if (sizes.length) {
          resize(image, sizes);
        } else {
          callback();
        }
      });
    });
  }

  if (src && Array.isArray(sizes)) {
    lwip.open(src, function(err, image) {
      resize(image, sizes);
    });
  } else {
    callback();
  }
};

module.exports = PwaManifestWebpackPlugin;
```

**Comment by easthing** [comment]
Think your help, has been modified and published

install new version fix bug

```
npm i pwa-manifest-webpack-plugin@1.0.2
```

**Comment by jonathaningram** [comment]
No problem, thanks for that!
